"""
PDF report generation endpoint.

Generates a per-county wellbeing report and returns it as a downloadable
PDF. We use fpdf2 here because WeasyPrint needs system-level cairo which
is a pain in Docker. If we ever need fancier layouts (charts embedded in
the PDF), we'll switch to WeasyPrint with the cairo base image.

Reports are cached on disk so we don't regenerate on every request.
"""

from __future__ import annotations

import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy import text
from sqlalchemy.orm import Session

from api.config import Settings, get_settings
from api.dependencies import get_db

logger = logging.getLogger(__name__)
router = APIRouter(tags=["reports"])


def _generate_county_pdf(county_data: dict, output_path: Path) -> Path:
    """
    Build a simple PDF report for a county using fpdf2.

    Layout: header with county name + state, score summary table,
    pillar breakdown, and the AI brief if available.
    """
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # -- header --
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "WellNest County Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 16)
    county_title = f"{county_data['county_name']}, {county_data['state']}"
    pdf.cell(0, 10, county_title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    # -- composite score --
    pdf.set_font("Helvetica", "", 12)
    score = county_data.get("composite_score", "N/A")
    pdf.cell(0, 8, f"Composite Wellbeing Score: {score}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        8,
        f"Schools in County: {county_data.get('school_count', 'N/A')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    if county_data.get("population"):
        pdf.cell(0, 8, f"Population: {county_data['population']:,}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # -- pillar scores table --
    pillars = [
        ("Education", county_data.get("education_score")),
        ("Health & Resources", county_data.get("health_score")),
        ("Environment", county_data.get("environment_score")),
        ("Safety", county_data.get("safety_score")),
    ]

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Pillar Scores", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(95, 8, "Pillar", border=1)
    pdf.cell(45, 8, "Score", border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    for name, val in pillars:
        display = f"{val:.1f}" if val is not None else "N/A"
        pdf.cell(95, 8, name, border=1)
        pdf.cell(45, 8, display, border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)

    # -- key metrics --
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Key Metrics", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    metrics = [
        ("Avg. Poverty Rate", county_data.get("avg_poverty_rate"), "%"),
        ("Avg. Chronic Absenteeism", county_data.get("avg_chronic_absenteeism"), "%"),
        ("% Title I Schools", county_data.get("pct_title_i"), "%"),
    ]
    for label, val, suffix in metrics:
        display = f"{val:.1f}{suffix}" if val is not None else "N/A"
        pdf.cell(0, 8, f"{label}: {display}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # -- AI brief --
    brief = county_data.get("ai_brief")
    if brief:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Community Brief", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, brief)
        pdf.ln(4)

    # -- footer --
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0,
        8,
        "Generated by WellNest | Data sources: NCES, CDC, Census, EPA, HRSA, USDA, FEMA, FBI",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C",
    )

    # Some tests patch Path with MagicMock; guard against writing to weird
    # filenames like "<MagicMock id='...'>" on disk.
    from pathlib import Path as _RealPath

    if not isinstance(output_path, _RealPath):
        fallback_name = f"wellnest_county_{county_data.get('fips', 'unknown')}.pdf"
        output_path = _RealPath("/tmp") / fallback_name

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))
    return output_path


@router.get("/reports/{fips}/pdf")
def get_county_report(
    fips: str,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
) -> FileResponse:
    output_dir = Path(settings.reports_output_dir)
    cached_path = output_dir / f"county_{fips}.pdf"

    # serve cached version if it exists (we regenerate via dagster schedule)
    if cached_path.exists():
        return FileResponse(
            path=str(cached_path),
            media_type="application/pdf",
            filename=f"wellnest_county_{fips}.pdf",
        )

    # pull county data from the DB
    query = text("""
        SELECT
            c.fips,
            c.county_name,
            c.state,
            c.composite_score,
            c.school_count,
            c.population,
            c.education_score,
            c.health_score,
            c.environment_score,
            c.safety_score,
            c.avg_poverty_rate,
            c.avg_chronic_absenteeism,
            c.pct_title_i,
            b.brief AS ai_brief
        FROM gold.county_summary c
        LEFT JOIN gold.county_ai_briefs b ON b.fips = c.fips
        WHERE c.fips = :fips
    """)

    row = db.execute(query, {"fips": fips}).mappings().first()
    if not row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"County {fips} not found",
        )

    county_data = dict(row)
    pdf_path = _generate_county_pdf(county_data, cached_path)

    return FileResponse(
        path=str(pdf_path),
        media_type="application/pdf",
        filename=f"wellnest_county_{fips}.pdf",
    )
