"""
Score, ranking, and anomaly models.

These back the rankings table, resource gap analysis, and anomaly detection
endpoints. Most of the actual computation lives in dbt gold models — the API
just reads and serializes.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from api.models.common import Pillar, ScoreCategory


class WellbeingScore(BaseModel):
    """Composite score with category label."""

    score: float = Field(..., ge=0, le=100)
    category: ScoreCategory
    national_percentile: int | None = Field(None, ge=0, le=100)


class PillarScore(BaseModel):
    pillar: Pillar
    score: float = Field(..., ge=0, le=100)
    weight: float = Field(..., ge=0, le=1, description="Pillar weight in composite calculation")
    category: ScoreCategory


class ScoreBreakdown(BaseModel):
    """Full breakdown returned on the school detail page."""

    composite: WellbeingScore
    pillars: list[PillarScore]
    data_completeness: float | None = Field(
        None,
        ge=0,
        le=1,
        description="Fraction of metrics that had actual data vs imputed",
    )


class RankingEntry(BaseModel):
    rank: int
    nces_id: str
    school_name: str
    city: str
    state: str
    composite_score: float = Field(..., ge=0, le=100)
    category: ScoreCategory
    score_change_1y: float | None = None


class ResourceGap(BaseModel):
    """
    Represents a gap between a school's needs and available resources.

    Built from gold.resource_gaps — we compare HPSA/MUA designations, food
    desert status, and poverty rate against available community resources.
    """

    nces_id: str
    school_name: str
    state: str
    county_fips: str
    gap_type: str = Field(
        ...,
        description="Type of gap: healthcare, food_access, mental_health, dental",
    )
    severity: float = Field(..., ge=0, le=100, description="Higher = more severe gap")
    composite_score: float
    description: str | None = None


class Anomaly(BaseModel):
    """
    A school flagged by isolation forest or z-score on YoY score change.

    The narrative is generated by GPT — explains why this school stands out.
    We found that abs(z) > 2.5 catches real issues about 70% of the time;
    the rest are usually data quality artifacts (enrollment spikes after
    school mergers, etc).
    """

    nces_id: str
    school_name: str
    state: str
    composite_score: float
    score_change_1y: float
    z_score: float
    anomaly_type: str = Field(
        ...,
        description="'improvement' or 'decline' — direction of the anomaly",
    )
    narrative: str | None = None
    detected_at: datetime | None = None
